from enum import Enum
from datetime import date
from decimal import Decimal
from pydantic import BaseModel, Field, EmailStr


class ModalidadOferta(str, Enum):
    PRESENCIAL = "Presencial"
    VIRTUAL = "Virtual"
    HIBRIDO = "Híbrido"


class TipoContrato(str, Enum):
    TERMINO_FIJO = "Término fijo"
    TERMINO_INDEFINIDO = "Término indefinido"
    PRESTACION_SERVICIOS = "Prestación de servicios"
    POR_OBRA = "Por obra"


class JornadaLaboral(str, Enum):
    TIEMPO_COMPLETO = "Tiempo completo"
    MEDIO_TIEMPO = "Medio tiempo"
    POR_HORAS = "Por horas"


class NivelExperiencia(str, Enum):
    SIN_EXPERIENCIA = "Sin experiencia"
    UNO_A_DOS_ANIOS = "1-2 años"
    TRES_A_CINCO_ANIOS = "3-5 años"
    MAS_DE_CINCO_ANIOS = "Más de 5 años"


class NivelEstudios(str, Enum):
    TECNICO = "Técnico"
    TECNOLOGICO = "Tecnológico"
    PREGRADO = "Pregrado"
    ESPECIALIZACION = "Especialización"
    MAESTRIA = "Maestría"
    DOCTORADO = "Doctorado"


class PaisOferta(str, Enum):
    AFGANISTAN = "Afganistán"
    ALBANIA = "Albania"
    ALEMANIA = "Alemania"
    ANDORRA = "Andorra"
    ANGOLA = "Angola"
    ANTIGUA_Y_BARBUDA = "Antigua y Barbuda"
    ARABIA_SAUDITA = "Arabia Saudita"
    ARGELIA = "Argelia"
    ARGENTINA = "Argentina"
    ARMENIA = "Armenia"
    AUSTRALIA = "Australia"
    AUSTRIA = "Austria"
    AZERBAIYAN = "Azerbaiyán"
    BAHAMAS = "Bahamas"
    BANGLADES = "Bangladés"
    BARBADOS = "Barbados"
    BAREIN = "Baréin"
    BELGICA = "Bélgica"
    BELICE = "Belice"
    BENIN = "Benin"
    BIELORRUSIA = "Bielorrusia"
    BIRMANIA = "Birmania (Myanmar)"
    BOLIVIA = "Bolivia"
    BOSNIA_Y_HERZEGOVINA = "Bosnia y Herzegovina"
    BOTSUANA = "Botsuana"
    BRASIL = "Brasil"
    BRUNEI = "Brunéi"
    BULGARIA = "Bulgaria"
    BURKINA_FASO = "Burkina Faso"
    BURUNDI = "Burundi"
    BUTAN = "Bután"
    CABO_VERDE = "Cabo Verde"
    CAMBOYA = "Camboya"
    CAMERUN = "Camerún"
    CANADA = "Canadá"
    CATAR = "Catar"
    CHAD = "Chad"
    CHILE = "Chile"
    CHINA = "China"
    CHIPRE = "Chipre"
    CIUDAD_DEL_VATICANO = "Ciudad del Vaticano"
    COLOMBIA = "Colombia"
    COMORAS = "Comoras"
    COREA_DEL_NORTE = "Corea del Norte"
    COREA_DEL_SUR = "Corea del Sur"
    COSTA_DE_MARFIL = "Costa de Marfil"
    COSTA_RICA = "Costa Rica"
    CROACIA = "Croacia"
    CUBA = "Cuba"
    DINAMARCA = "Dinamarca"
    DOMINICA = "Dominica"
    ECUADOR = "Ecuador"
    EGIPTO = "Egipto"
    EL_SALVADOR = "El Salvador"
    EMIRATOS_ARABES_UNIDOS = "Emiratos Árabes Unidos"
    ERITREA = "Eritrea"
    ESLOVAQUIA = "Eslovaquia"
    ESLOVENIA = "Eslovenia"
    ESPANA = "España"
    ESTADOS_UNIDOS = "Estados Unidos"
    ESTONIA = "Estonia"
    ETIOPIA = "Etiopía"
    FILIPINAS = "Filipinas"
    FINLANDIA = "Finlandia"
    FIYI = "Fiyi"
    FRANCIA = "Francia"
    GABON = "Gabón"
    GAMBIA = "Gambia"
    GEORGIA = "Georgia"
    GHANA = "Ghana"
    GRANADA = "Granada"
    GRECIA = "Grecia"
    GUATEMALA = "Guatemala"
    GUINEA = "Guinea"
    GUINEA_ECUATORIAL = "Guinea Ecuatorial"
    GUINEA_BISAU = "Guinea-Bisáu"
    GUYANA = "Guyana"
    HAITI = "Haití"
    HONDURAS = "Honduras"
    HUNGRIA = "Hungría"
    INDIA = "India"
    INDONESIA = "Indonesia"
    IRAK = "Irak"
    IRAN = "Irán"
    IRLANDA = "Irlanda"
    ISLANDIA = "Islandia"
    ISLAS_MARSHALL = "Islas Marshall"
    ISLAS_SALOMON = "Islas Salomón"
    ISRAEL = "Israel"
    ITALIA = "Italia"
    JAMAICA = "Jamaica"
    JAPON = "Japón"
    JORDANIA = "Jordania"
    KAZAJISTAN = "Kazajistán"
    KENIA = "Kenia"
    KIRGUISTAN = "Kirguistán"
    KIRIBATI = "Kiribati"
    KUWAIT = "Kuwait"
    LAOS = "Laos"
    LESOTO = "Lesoto"
    LETONIA = "Letonia"
    LIBANO = "Líbano"
    LIBERIA = "Liberia"
    LIBIA = "Libia"
    LIECHTENSTEIN = "Liechtenstein"
    LITUANIA = "Lituania"
    LUXEMBURGO = "Luxemburgo"
    MACEDONIA_DEL_NORTE = "Macedonia del Norte"
    MADAGASCAR = "Madagascar"
    MALASIA = "Malasia"
    MALAWI = "Malawi"
    MALDIVAS = "Maldivas"
    MALI = "Malí"
    MALTA = "Malta"
    MARRUECOS = "Marruecos"
    MAURICIO = "Mauricio"
    MAURITANIA = "Mauritania"
    MEXICO = "México"
    MICRONESIA = "Micronesia"
    MOLDAVIA = "Moldavia"
    MONACO = "Mónaco"
    MONGOLIA = "Mongolia"
    MONTENEGRO = "Montenegro"
    MOZAMBIQUE = "Mozambique"
    NAMIBIA = "Namibia"
    NAURU = "Nauru"
    NEPAL = "Nepal"
    NICARAGUA = "Nicaragua"
    NIGER = "Niger"
    NIGERIA = "Nigeria"
    NORUEGA = "Noruega"
    NUEVA_ZELANDA = "Nueva Zelanda"
    OMAN = "Omán"
    PAISES_BAJOS = "Países Bajos"
    PAKISTAN = "Pakistán"
    PALAOS = "Palaos"
    PANAMA = "Panamá"
    PAPUA_NUEVA_GUINEA = "Papúa Nueva Guinea"
    PARAGUAY = "Paraguay"
    PERU = "Perú"
    POLONIA = "Polonia"
    PORTUGAL = "Portugal"
    REINO_UNIDO = "Reino Unido"
    REPUBLICA_CENTROAFRICANA = "República Centroafricana"
    REPUBLICA_CHECA = "República Checa"
    REPUBLICA_DEL_CONGO = "República del Congo"
    REPUBLICA_DEMOCRATICA_DEL_CONGO = "República Democrática del Congo"
    REPUBLICA_DOMINICANA = "República Dominicana"
    RUANDA = "Ruanda"
    RUMANIA = "Rumanía"
    RUSIA = "Rusia"
    SAMOA = "Samoa"
    SAN_CRISTOBAL_Y_NIEVES = "San Cristóbal y Nieves"
    SAN_MARINO = "San Marino"
    SAN_VICENTE_Y_LAS_GRANADINAS = "San Vicente y las Granadinas"
    SANTA_LUCIA = "Santa Lucía"
    SANTO_TOME_Y_PRINCIPE = "Santo Tomé y Príncipe"
    SENEGAL = "Senegal"
    SERBIA = "Serbia"
    SEYCHELLES = "Seychelles"
    SIERRA_LEONA = "Sierra Leona"
    SINGAPUR = "Singapur"
    SIRIA = "Siria"
    SOMALIA = "Somalia"
    SRI_LANKA = "Sri Lanka"
    SUAZILANDIA = "Suazilandia (Eswatini)"
    SUDAFRICA = "Sudáfrica"
    SUDAN = "Sudán"
    SUDAN_DEL_SUR = "Sudán del Sur"
    SUECIA = "Suecia"
    SUIZA = "Suiza"
    SURINAM = "Surinam"
    TAILANDIA = "Tailandia"
    TANZANIA = "Tanzania"
    TAYIKISTAN = "Tayikistán"
    TIMOR_ORIENTAL = "Timor Oriental"
    TOGO = "Togo"
    TONGA = "Tonga"
    TRINIDAD_Y_TOBAGO = "Trinidad y Tobago"
    TUNEZ = "Túnez"
    TURKMENISTAN = "Turkmenistán"
    TURQUIA = "Turquía"
    TUVALU = "Tuvalu"
    UCRANIA = "Ucrania"
    UGANDA = "Uganda"
    URUGUAY = "Uruguay"
    UZBEKISTAN = "Uzbekistán"
    VANUATU = "Vanuatu"
    VENEZUELA = "Venezuela"
    VIETNAM = "Vietnam"
    YEMEN = "Yemen"
    YIBUTI = "Yibuti"
    ZAMBIA = "Zambia"
    ZIMBABWE = "Zimbabwe"


class OfertaLaboral(BaseModel):
    idOferta: int
    tituloOferta: str = Field(min_length=5, max_length=150, pattern=r"^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9\s\-\.]+$")
    nombreEmpresa: str = Field(min_length=3, max_length=150, pattern=r"^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9\s\-\.&]+$")
    descripcionOferta: str = Field(min_length=10, max_length=1000, pattern=r"^[A-Za-zñÑáéíóúÁÉÍÓÚ0-9\s,.!?¿¡:;()\-\"\'\+@#]+$")
    salarioOfrecido: Decimal = Field(ge=0)
    ciudadOferta: str = Field(default=None, min_length=3, max_length=100, pattern=r"^[A-Za-zñÑáéíóúÁÉÍÓÚ\s]+$")
    paisOferta: PaisOferta
    fechaPublicacion: date
    modalidadOferta: ModalidadOferta
    tipoContrato: TipoContrato
    jornadaLaboral: JornadaLaboral
    nivelExperiencia: NivelExperiencia
    nivelEstudios: NivelEstudios
    correoContacto: EmailStr = Field(min_length=6, max_length=150)

